version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:v1.9.0
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage:rw
